services:
  scylla:
    container_name: scylla
    image: scylladb/scylla:6.0.1
    command: --smp 1 --memory 750M --overprovisioned 1
    ports:
      - 9042:9042
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "cqlsh", "-e describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 15

  scylla-load-keyspace:
    container_name: scylla-load-keyspace
    image: scylladb/scylla:6.0.1
    depends_on:
      scylla:
        condition: service_healthy
    volumes:
      - ./cql/schema.cql:/schema.cql
      - ./cql/data-samples.cql:/data-samples.cql
    entrypoint: ''
    command: /bin/bash -c "
        echo loading keyspace
        && cqlsh scylla -f /schema.cql
        && echo loading sample data...
        && cqlsh scylla -f /data-samples.cql
      "

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true

